src/objects/Workshop__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Workshop</label>
    <nameField>
        <label>Workshop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workshops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/CsUpsertWorkshop.cls
public with sharing class CsUpsertWorkshop implements Queueable, Database.AllowsCallouts{
    private CsTomeksWorkshopsRestController.WrappedTomeksWorkshop tomeksWorkshop;
    private Workshop__c workshopToUpsert;


    public CsUpsertWorkshop(CsTomeksWorkshopsRestController.WrappedTomeksWorkshop tomeksWorkshop){
        this.tomeksWorkshop = tomeksWorkshop;
        this.workshopToUpsert = new Workshop__c();
    }

    public void execute(QueueableContext context){
        workshopToUpsert.External_Id__c = tomeksWorkshop.id;
        workshopToUpsert.Name = tomeksWorkshop.name;
        workshopToUpsert.Website__c = tomeksWorkshop.website;
        workshopToUpsert.Phone__c = tomeksWorkshop.phone;
        workshopToUpsert.City__c = tomeksWorkshop.city;
        workshopToUpsert.Country__c = tomeksWorkshop.country;
        workshopToUpsert.Zip_Code__c = tomeksWorkshop.zipCode;
        workshopToUpsert.Id = tomeksWorkshop.externalId;
        workshopToUpsert.Is_Synchronized__c = false;
        try {
            upsert workshopToUpsert;
        } catch (Exception err) {
            System.debug(err.getMessage());
        }
    }
}