src/objects/Workshop__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <label>Workshop</label>
    <nameField>
        <label>Workshop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workshops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/CsCountryRest.cls
@RestResource(urlMapping='/workshops/countries/*')
global class CsCountryRest {

    @HttpGet
    global static List<String> getCountries(){
        List<String> countries = new List<String>();
        Schema.DescribeFieldResult describeFieldResult = Workshop__c.Country__c.getDescribe();
        Schema.sObjectField sObjectField = describeFieldResult.getSObjectField();
        List<PicklistEntry> entries = sObjectField.getDescribe().getPicklistValues();
        for (PicklistEntry picklistEntry : entries) {
            countries.add(picklistEntry.getValue());
        }
        return countries;
    }
}